### ISSUE TITLE
加工先を変更できないバグ

### ISSUE THREAD

**Issue by daima3629** [sevenc-nanashi/double-alt-death#1]
右Shiftを押しながら2回Altを押すと画面左上に変更用ウィンドウが出てくるが、選択するためボタンを押すとウィンドウが閉じてしまい、強制的に「突然の死」になってしまう。ちなみにだが最小化ボタンを押しても閉じてしまう。
改善していただきたい。

**Comment by sevenc-nanashi** [comment]
修正しました。
（最小化ボタンを押しても閉じるのは仕様）
